installed_libraries:
- name: absl-py
  version: 2.2.2
- name: aiohappyeyeballs
  version: 2.6.1
- name: aiohttp
  version: 3.11.16
- name: aiosignal
  version: 1.3.2
- name: alembic
  version: 1.14.1
- name: anyio
  version: 3.7.1
- name: astunparse
  version: 1.6.3
- name: async-timeout
  version: 5.0.1
- name: attrs
  version: 25.3.0
- name: cachetools
  version: 5.5.2
- name: certifi
  version: 2025.1.31
- name: cfgv
  version: 3.4.0
- name: charset-normalizer
  version: 3.4.1
- name: chex
  version: 0.1.6
- name: cloudpickle
  version: 3.1.1
- name: colorama
  version: 0.4.6
- name: coloredlogs
  version: 15.0.1
- name: colorlog
  version: 6.9.0
- name: commonmark
  version: 0.9.1
- name: coverage
  version: 7.8.0
- name: cycler
  version: 0.12.1
- name: dataclasses-json
  version: 0.5.7
- name: datasets
  version: 2.3.2
- name: decorator
  version: 5.1.1
- name: deprecation
  version: 2.1.0
- name: dill
  version: 0.3.5.1
- name: distlib
  version: 0.3.9
- name: distro
  version: 1.8.0
- name: dm-tree
  version: 0.1.9
- name: docopt
  version: 0.6.2
- name: elastic-transport
  version: 8.17.1
- name: elasticsearch
  version: 8.11.0
- name: exceptiongroup
  version: 1.2.2
- name: fastapi
  version: 0.103.2
- name: fastnumbers
  version: 5.1.1
- name: filelock
  version: 3.18.0
- name: flatbuffers
  version: 23.5.26
- name: flax
  version: 0.6.0
- name: fonttools
  version: 4.57.0
- name: frozenlist
  version: 1.5.0
- name: fsspec
  version: 2025.3.2
- name: fuzzywuzzy
  version: 0.18.0
- name: gast
  version: 0.4.0
- name: google-auth
  version: 2.38.0
- name: google-auth-oauthlib
  version: 1.0.0
- name: google-pasta
  version: 0.2.0
- name: graphviz
  version: 0.8.4
- name: greenlet
  version: 3.1.1
- name: grpcio
  version: 1.71.0
- name: h5py
  version: 3.13.0
- name: huggingface-hub
  version: 0.30.2
- name: humanfriendly
  version: '10.0'
- name: identify
  version: 2.6.9
- name: idna
  version: '3.10'
- name: importlib-resources
  version: 6.1.1
- name: jax
  version: 0.4.13
- name: jaxlib
  version: 0.4.11
- name: Jinja2
  version: 3.1.6
- name: joblib
  version: 1.4.2
- name: keras
  version: 2.13.1
- name: kiwisolver
  version: 1.4.8
- name: Levenshtein
  version: 0.27.1
- name: libclang
  version: 18.1.1
- name: lightning
  version: 2.5.1
- name: lightning-utilities
  version: 0.14.3
- name: linkify-it-py
  version: 2.0.3
- name: loguru
  version: 0.5.3
- name: Mako
  version: 1.3.10
- name: Markdown
  version: '3.8'
- name: markdown-it-py
  version: 3.0.0
- name: MarkupSafe
  version: 3.0.2
- name: marshmallow
  version: 3.26.1
- name: marshmallow-enum
  version: 1.5.1
- name: matplotlib
  version: 3.5.1
- name: mdit-py-plugins
  version: 0.4.2
- name: mdurl
  version: 0.1.2
- name: ml-dtypes
  version: 0.2.0
- name: mpmath
  version: 1.3.0
- name: msgpack
  version: 1.1.0
- name: multidict
  version: 6.4.3
- name: multiprocess
  version: 0.70.13
- name: mxnet
  version: 1.9.1
- name: mypy-extensions
  version: 1.0.0
- name: networkx
  version: 2.8.5
- name: nodeenv
  version: 1.9.1
- name: numpy
  version: 1.23.1
- name: oauthlib
  version: 3.2.2
- name: onnx
  version: 1.15.0
- name: onnxruntime
  version: 1.16.3
- name: opencv-python
  version: 4.11.0.86
- name: opencv-python-headless
  version: 4.6.0.66
- name: opt_einsum
  version: 3.4.0
- name: optax
  version: 0.1.7
- name: optuna
  version: 3.6.2
- name: packaging
  version: '24.2'
- name: pandas
  version: 1.5.3
- name: patsy
  version: 1.0.1
- name: pillow
  version: 11.2.1
- name: pip
  version: '24.0'
- name: platformdirs
  version: 4.3.7
- name: pre-commit
  version: 3.5.0
- name: prettytable
  version: 3.0.0
- name: prompt_toolkit
  version: 3.0.50
- name: propcache
  version: 0.3.1
- name: protobuf
  version: 3.20.3
- name: psutil
  version: 5.9.6
- name: py-cpuinfo
  version: 9.0.0
- name: pyarrow
  version: 19.0.1
- name: pyasn1
  version: 0.6.1
- name: pyasn1_modules
  version: 0.4.2
- name: pybind11
  version: 2.6.2
- name: pybuda
  version: 0.1.240401+dev.gs.c7ce1e7
- name: pydantic
  version: 1.10.21
- name: pyelftools
  version: '0.32'
- name: Pygments
  version: 2.19.1
- name: pyinstrument
  version: 4.1.1
- name: pyluwen
  version: 0.7.1
- name: pyparsing
  version: 3.2.3
- name: python-dateutil
  version: 2.9.0.post0
- name: python-Levenshtein
  version: 0.27.1
- name: pytorch-forecasting
  version: 1.0.0
- name: pytorch-lightning
  version: 2.5.1
- name: pytorch_optimizer
  version: 2.12.0
- name: pytz
  version: '2025.2'
- name: PyYAML
  version: 6.0.2
- name: pyzmq
  version: 26.4.0
- name: RapidFuzz
  version: 3.13.0
- name: rapidyaml
  version: 0.9.0
- name: regex
  version: 2024.11.6
- name: requests
  version: 2.28.2
- name: requests-oauthlib
  version: 2.0.0
- name: responses
  version: 0.18.0
- name: rich
  version: 11.2.0
- name: rsa
  version: '4.9'
- name: safetensors
  version: 0.5.3
- name: scikit-learn
  version: 1.6.1
- name: scipy
  version: 1.8.0
- name: seaborn
  version: 0.13.2
- name: setuptools
  version: 65.5.0
- name: six
  version: 1.17.0
- name: sniffio
  version: 1.3.1
- name: sortedcontainers
  version: 2.4.0
- name: SQLAlchemy
  version: 2.0.24
- name: starlette
  version: 0.27.0
- name: statsmodels
  version: 0.14.4
- name: sympy
  version: 1.13.3
- name: tabulate
  version: 0.9.0
- name: tensorboard
  version: 2.13.0
- name: tensorboard-data-server
  version: 0.7.2
- name: tensorflow-cpu
  version: 2.13.0
- name: tensorflow-estimator
  version: 2.13.0
- name: tensorflow-io-gcs-filesystem
  version: 0.37.1
- name: termcolor
  version: 3.0.1
- name: textual
  version: 0.59.0
- name: tf2onnx
  version: 1.15.1
- name: tflite
  version: 2.10.0
- name: threadpoolctl
  version: 3.6.0
- name: tokenizers
  version: 0.15.2
- name: toolz
  version: 1.0.0
- name: torch
  version: 2.1.0+cpu.cxx11.abi
- name: torchmetrics
  version: 1.7.1
- name: torchvision
  version: 0.16.0+fbb4cc5
- name: tornado
  version: 6.4.2
- name: tqdm
  version: 4.66.3
- name: transformers
  version: 4.35.2
- name: tt-smi
  version: 3.0.12
- name: tt-tools-common
  version: 1.4.14
- name: tvm
  version: 0.14.0+dev.tt.dfda3826c
- name: typing_extensions
  version: 4.5.0
- name: typing-inspect
  version: 0.9.0
- name: uc-micro-py
  version: 1.0.3
- name: ultralytics
  version: 8.0.145
- name: urllib3
  version: 1.26.14
- name: virtualenv
  version: 20.30.0
- name: wcwidth
  version: 0.2.13
- name: Werkzeug
  version: 3.1.3
- name: wheel
  version: 0.45.1
- name: wrapt
  version: 1.17.2
- name: xxhash
  version: 3.5.0
- name: yarl
  version: 1.19.0
python_info:
  python_executable: /home/spook/venvs/tt-gs-prebuilt/bin/python
  python_version: 3.10.13
